#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }


if ARGV.length == 0
  choose do |menu|
      menu.prompt = ""
      games_controller = GamesController.new
      menu.choice('List Owned Games - owned') { games_controller.index }
      menu.choice('List Wanted Games - wanted') { say("") }
      menu.choice('Manage DB - manage') { say("") }
      menu.choice('Exit') { say("Later!\n") }
    end

elsif ARGV.length == 1
  if ARGV[0] != 'owned' && ARGV[0] != 'wanted' && ARGV[0] != 'manage'
    print "[Help] Run as: ./video_game_tracker  with no arguements"
  elsif ARGV[0] == 'manage'
    choose do |menu|
      menu.prompt = ""
      menu.choice('Add A Game') { say("") }
      menu.choice('Update A Game') { say("") }
      menu.choice('Delete A Game') { say("") }
      menu.choice('List All Games') { say("") }
      menu.choice('Exit') { say("Later!\n") }
    end
  end

end
