#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }


if ARGV.length == 0
  choose do |menu|
      menu.prompt = ""
      games_controller = GamesController.new

      menu.choice('List Owned Games - owned') do
          say (games_controller.index)
          exit
      end

      menu.choice('List Wanted Games - wanted') { say("") }
      menu.choice('Manage DB - manage') { say("") }
      menu.choice('Exit') { say("Later!\n") }
    end

elsif ARGV.length == 1
  if ARGV[0] != 'owned' && ARGV[0] != 'wanted' && ARGV[0] != 'manage'
    print "[Help] Run as: ./video_game_tracker  with no arguements"
  elsif ARGV[0] == 'manage'
    loop do
      choose do |menu|
        menu.prompt = ""
        games_controller = GamesController.new

        menu.choice('Add A Game') do
          user_input = ask ("What game would you like to add?")
          response = games_controller.add(user_input)
          say(response) unless response.nil?
          # if /has\sbeen\sadded$/.match(response)
          #   break
          # end
        end

        menu.choice('Update A Game') do
          say (games_controller.index)
          exit
        end

        menu.choice('Delete A Game') { say("") }

        menu.choice('List All Games') do
          say (games_controller.index)
          exit
        end

        menu.choice('Exit') do
          say("Later!\n")
          exit
        end
      end
    end
  end
end
